version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  connect:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: test
      - run: |
          mkdir env
          aws s3 cp s3://my-bucket-from-github-c436186/dev/dev.txt ./env/
          cd env
          pwd
      - persist_to_workspace:
          root: env
          paths: env/dev.txt
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: |
          python3 main-test.py
#          cat /tmp/workspace/env/dev

workflows:
  build_and_test:
    jobs:
      - connect
      - build
      - test:
          requires:
            - build
