version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  connect:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: test
      - run: |
          
          if [[ $CIRCLE_BRANCH == "dev" ]]; then export PATH_TO_ENV=dev/dev.txt; 
          elif[[ $CIRCLE_BRANCH == "stg" ]]; then export PATH_TO_ENV=stg/stg.txt;
          elif[[ $CIRCLE_BRANCH == "prod" ]]; then export PATH_TO_ENV=prod/prod.txt;

          mkdir env
          aws s3 cp s3://my-bucket-from-github-c436186/$PATH_TO_ENV ./env/
          cd env
      - persist_to_workspace:
          root: env
          paths: dev.txt

  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - attach_workspace:
          at: circleci-python/env 
      - run: |
          ls circleci-python/env
          python3 main.py
      

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout 
      - run: |
          python3 main-test.py
          

workflows:
  build_and_test:
    jobs:
      - connect
      - build:
          requires:
            - connect
      - test:
          requires:
            - build
